version: 2
project_name: mtx

builds:
  - main: ./cmd/mtx
    binary: mtx
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: zoobzio
    name: mtx
  draft: false
  prerelease: auto
  mode: append
